export const skillCategories = [
  'Programming Languages',
  'Web Development',
  'Mobile Development',
  'Data Science & AI',
  'DevOps & Cloud',
  'Design',
  'Marketing',
  'Business',
  'Soft Skills',
] as const;

export const skills = {
  'Programming Languages': [
    'JavaScript',
    'Python',
    'Java',
    'C++',
    'C#',
    'Go',
    'Rust',
    'TypeScript',
    'PHP',
    'Ruby',
    'Swift',
    'Kotlin',
    'Dart',
    'Scala',
    'R',
  ],
  'Web Development': [
    'React',
    'Next.js',
    'Vue.js',
    'Angular',
    'Node.js',
    'Express.js',
    'Django',
    'Flask',
    'FastAPI',
    'Laravel',
    'Spring Boot',
    'ASP.NET',
    'HTML/CSS',
    'Tailwind CSS',
    'Bootstrap',
    'Sass',
    'Webpack',
    'GraphQL',
    'REST API',
  ],
  'Mobile Development': [
    'React Native',
    'Flutter',
    'iOS Development',
    'Android Development',
    'Xamarin',
    'Ionic',
    'SwiftUI',
    'Jetpack Compose',
  ],
  'Data Science & AI': [
    'Machine Learning',
    'Deep Learning',
    'TensorFlow',
    'PyTorch',
    'Pandas',
    'NumPy',
    'Scikit-learn',
    'Natural Language Processing',
    'Computer Vision',
    'Data Analysis',
    'Statistical Modeling',
  ],
  'DevOps & Cloud': [
    'Docker',
    'Kubernetes',
    'AWS',
    'Azure',
    'Google Cloud',
    'CI/CD',
    'Jenkins',
    'Git',
    'GitHub Actions',
    'Terraform',
    'Ansible',
    'Linux',
  ],
  'Design': [
    'UI/UX Design',
    'Figma',
    'Adobe XD',
    'Sketch',
    'Photoshop',
    'Illustrator',
    'Wireframing',
    'Prototyping',
    'User Research',
    'Design Systems',
  ],
  'Marketing': [
    'Digital Marketing',
    'SEO',
    'Content Marketing',
    'Social Media Marketing',
    'Email Marketing',
    'Google Analytics',
    'PPC Advertising',
    'Marketing Strategy',
    'Growth Hacking',
  ],
  'Business': [
    'Project Management',
    'Product Management',
    'Business Analysis',
    'Agile/Scrum',
    'Financial Analysis',
    'Strategic Planning',
    'Market Research',
    'Stakeholder Management',
  ],
  'Soft Skills': [
    'Communication',
    'Leadership',
    'Problem Solving',
    'Teamwork',
    'Time Management',
    'Critical Thinking',
    'Adaptability',
    'Creativity',
  ],
} as const;

export const skillLevels = [
  { value: 'beginner', label: 'Beginner', description: '0-1 years experience' },
  { value: 'intermediate', label: 'Intermediate', description: '1-3 years experience' },
  { value: 'advanced', label: 'Advanced', description: '3-5 years experience' },
  { value: 'expert', label: 'Expert', description: '5+ years experience' },
] as const;

export const popularSkills = [
  'JavaScript',
  'React',
  'Python',
  'Node.js',
  'TypeScript',
  'Next.js',
  'AWS',
  'Docker',
  'Machine Learning',
  'UI/UX Design',
  'MongoDB',
  'PostgreSQL',
  'GraphQL',
  'Flutter',
  'React Native',
];

export const inDemandSkills = [
  'Artificial Intelligence',
  'Machine Learning',
  'Blockchain',
  'Cybersecurity',
  'Cloud Computing',
  'DevOps',
  'Data Science',
  'Full Stack Development',
  'Mobile Development',
  'UI/UX Design',
];

export type SkillCategory = typeof skillCategories[number];
export type SkillLevel = typeof skillLevels[number]['value'];