'use client';

import React, { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { CheckCircle, XCircle, Award, TrendingUp, Clock, Share2, Download, RotateCcw } from 'lucide-react';
import { QuestionDisplay } from './QuestionDisplay';

export function ResultsDisplay({ results, badge, onRetry, onShare, onDownload }: any) {
  const [selectedQuestion, setSelectedQuestion] = useState<number | null>(null);
  const formatTime = (seconds: number) => { const mins = Math.floor(seconds / 60); const secs = seconds % 60; return `${mins}m ${secs}s`; };
  const correctCount = results.questions.filter((q: any) => q.isCorrect).length;
  const accuracy = Math.round((correctCount / results.questions.length) * 100);

  return (
    <div className="space-y-6">
      <div className="text-center">{results.passed ? (<><div className="mb-4 flex justify-center"><div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center"><CheckCircle className="h-10 w-10 text-green-600" /></div></div><h1 className="text-2xl font-bold">🎉 Congratulations! You Passed!</h1><p className="text-gray-600">You've successfully completed the assessment</p></>) : (<><div className="mb-4 flex justify-center"><div className="w-20 h-20 bg-red-100 rounded-full flex items-center justify-center"><XCircle className="h-10 w-10 text-red-600" /></div></div><h1 className="text-2xl font-bold">Assessment Completed</h1><p className="text-gray-600">Keep practicing and try again</p></>)}</div>
      <Card className="p-6"><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div className="text-center"><p className="text-sm text-gray-500 mb-2">Your Score</p><div className="relative inline-flex"><svg className="w-32 h-32" viewBox="0 0 128 128"><circle className="text-gray-200" strokeWidth="8" stroke="currentColor" fill="transparent" r="56" cx="64" cy="64" /><circle className={results.passed ? 'text-green-500' : 'text-red-500'} strokeWidth="8" strokeDasharray={2 * Math.PI * 56} strokeDashoffset={2 * Math.PI * 56 * (1 - results.score / 100)} strokeLinecap="round" stroke="currentColor" fill="transparent" r="56" cx="64" cy="64" /></svg><span className="absolute inset-0 flex items-center justify-center text-2xl font-bold">{results.score}%</span></div></div><div className="space-y-4"><div><p className="text-sm text-gray-500">Passing Score</p><p className="text-lg font-semibold">{results.passingScore}%</p></div><div><p className="text-sm text-gray-500">Time Taken</p><p className="text-lg font-semibold">{formatTime(results.timeSpent)}</p></div><div><p className="text-sm text-gray-500">Points Earned</p><p className="text-lg font-semibold">{results.earnedPoints}/{results.totalPoints}</p></div></div></div><div className="mt-4"><div className="flex justify-between text-sm mb-1"><span>Score</span><span>{results.score}%</span></div><div className="w-full bg-gray-200 rounded-full h-2"><div className={`h-2 rounded-full ${results.passed ? 'bg-green-500' : 'bg-red-500'}`} style={{ width: `${results.score}%` }} /></div></div></Card>
      {badge && <Card className="p-6 bg-gradient-to-r from-yellow-50 to-orange-50"><div className="flex items-center gap-4"><div className="p-3 bg-yellow-100 rounded-full"><Award className="h-8 w-8 text-yellow-600" /></div><div className="flex-1"><h3 className="font-semibold text-lg">🏆 Badge Earned!</h3><p className="text-xl font-bold text-yellow-700">{badge.name}</p><p className="text-sm text-gray-600">{badge.description}</p></div><Button variant="outline" onClick={onShare}><Share2 className="h-4 w-4 mr-2" />Share</Button></div></Card>}
      {results.trustScoreIncreased > 0 && <Card className="p-4 bg-green-50 border-green-200"><div className="flex items-center gap-3"><TrendingUp className="h-6 w-6 text-green-600" /><div><p className="font-medium text-green-800">Trust Score Increased!</p><p className="text-sm text-green-700">You earned +{results.trustScoreIncreased} points</p></div></div></Card>}
      <Card className="p-6"><h2 className="text-lg font-semibold mb-4">Performance Stats</h2><div className="grid grid-cols-3 gap-4 text-center"><div><p className="text-2xl font-bold text-green-600">{correctCount}</p><p className="text-xs text-gray-500">Correct</p></div><div><p className="text-2xl font-bold text-red-600">{results.questions.length - correctCount}</p><p className="text-xs text-gray-500">Incorrect</p></div><div><p className="text-2xl font-bold text-blue-600">{accuracy}%</p><p className="text-xs text-gray-500">Accuracy</p></div></div></Card>
      <Card className="p-6"><div className="flex items-center justify-between mb-4"><h2 className="text-lg font-semibold">Question Review</h2>{selectedQuestion !== null && <Button variant="ghost" size="sm" onClick={() => setSelectedQuestion(null)}>Back to Summary</Button>}</div>{selectedQuestion !== null ? <QuestionDisplay question={results.questions[selectedQuestion]} index={selectedQuestion} totalQuestions={results.questions.length} selectedAnswer={results.questions[selectedQuestion].userAnswer} showExplanation={true} readOnly={true} isCorrect={results.questions[selectedQuestion].isCorrect} onAnswer={() => {}} /> : <div className="space-y-3">{results.questions.map((q: any, idx: number) => (<button key={idx} onClick={() => setSelectedQuestion(idx)} className="w-full text-left p-3 border rounded-lg hover:bg-gray-50 transition-colors"><div className="flex items-center gap-3">{q.isCorrect ? <CheckCircle className="h-5 w-5 text-green-500 shrink-0" /> : <XCircle className="h-5 w-5 text-red-500 shrink-0" />}<div className="flex-1 min-w-0"><p className="text-sm font-medium truncate">{q.question}</p><div className="flex items-center gap-2 mt-1"><span className="text-xs text-gray-500">Points: {q.isCorrect ? q.points : 0}/{q.points}</span></div></div></div></button>))}</div>}</Card>
      <div className="flex flex-wrap gap-4 justify-center">{onRetry && <Button onClick={onRetry}><RotateCcw className="mr-2 h-4 w-4" />Retake Assessment</Button>}{onShare && <Button variant="outline" onClick={onShare}><Share2 className="mr-2 h-4 w-4" />Share Results</Button>}{onDownload && <Button variant="outline" onClick={onDownload}><Download className="mr-2 h-4 w-4" />Download Certificate</Button>}</div>
    </div>
  );
}